# Generated by Django 6.0 on 2026-01-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='registrations.event'),
        ),
    ]
