# Generated by Django 6.0 on 2026-01-31 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_companyprofile_remove_courseenrollment_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to='registrations.invoice'),
        ),
    ]
